export const app = {
   SET_DARK_MODE: 'SET_DARK_MODE',
};

export const user = {
   REQUEST_GET_USERS: 'REQUEST_GET_USERS',
   REQUEST_GET_USER: 'REQUEST_GET_USER',
   REQUEST_EDIT_USER: 'REQUEST_EDIT_USER',
   REQUEST_DELETE_USER: 'REQUEST_DELETE_USER',

   SET_USERS_LOADING: 'SET_USERS_LOADING',

   SET_USERS: 'SET_USERS',
   SET_USER: 'SET_USER',
};
